### PR TITLE
Update return section

### PR DESCRIPTION
**Pull request by syffer**
not sure what 'ret_name' represents in the function update_return_type()

### CODE REVIEW

**Comment by KristoforMaynard** [comment]
I believe ret_name is specific to the Numpy style. In this style, I have seen some examples of people naming the return value. This doesn't really make sense to me, but I try not to impose my sense of style on other projects.

I don't understand this PR since...
- I can't seem to reproduce the bug it purportedly fixes.
- It introduces a bug that it overwrites the return type to the default on every update. 
- It removes user-entered text if it can't find the 'return' / 'yield' keywords. I would prefer this text be moved to a different section that the user can remove themselves.

**Comment by syffer** [comment]
the bug that  e9fe80b should fix is the following : 

- during a convertion, with an already existing return section and a different return keyword (e.g. a "Return" section exists, but the user change to a 'yield' keyword), the name of the return section isn't changed (for the example, it is still a "Return" section)


- for example, after converting this to numpy : 
```
def test(): 
    """Summary
    
    Returns:
        TYPE: Description
    """
    yield 1
```

- we get this result, the wrong formatter is used here : 
```
def test(): 
    """Summary
    
    Returns
    -------
    TYPE
        Description
    """
    yield 1
```

**Comment by syffer** [comment]
The removed return sections are added for numpy and google (as "No Longer Returned" and 'No Longer Yielded').
The error should also be fixed.

**Comment by KristoforMaynard** [comment]
Wicked - looks good :)

**Pull request merged**
